---

version: "3.3"
services:
  redis:
    image: redis
    restart: always
    expose:
      - 6379
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/data
  simon_says:
    container_name: simon_says
    build:
      context: .
    depends_on:
      - redis
    restart: always
    expose:
      - 5060
      - 8000
    volumes:
      - ./config.ini:/etc/simon_says.ini
      - ./asterisk_configs:/etc/asterisk
    network_mode: host
