---

version: "3.3"
services:
  redis:
    image: redis
    restart: always
    expose:
      - 6379
    network_mode: host
  simon_says_test:
    container_name: simon_says_test
    build:
      context: .
      dockerfile: Dockerfile.test
    command: tox -v -e lint,py37
    depends_on:
      - redis
    restart: always
    network_mode: host
