---

version: "3.3"
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/data
    network_mode: host
  simon_says:
    container_name: simon_says
    build:
      context: .
    depends_on:
      - redis
    restart: always
    volumes:
      - ./config.ini:/etc/simon_says.ini
      - ./asterisk_configs:/etc/asterisk
      - ./logs:/app/logs
    network_mode: host
