---

version: "3.3"
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
  simon_says_test:
    container_name: simon_says_test
    build:
      context: .
      dockerfile: test/Dockerfile
    command: tox -v -e lint,py37
    depends_on:
      - redis
    restart: always
