"""
ContactID codes from: http://www.voip-sip-sdk.com/attachments/583/contact_id.pdf
"""

CODES = {
    "100": {"name": "Medical Zone", "type": "zone"},
    "101": {"name": "Personal Emergency Zone", "type": "zone"},
    "102": {"name": "Fail to report in Zone", "type": "zone"},
    "110": {"name": "Fire Zone", "type": "zone"},
    "111": {"name": "Smoke Zone", "type": "zone"},
    "112": {"name": "Combustion Zone", "type": "zone"},
    "113": {"name": "Water flow Zone", "type": "zone"},
    "114": {"name": "Heat Zone", "type": "zone"},
    "115": {"name": "Pull Station Zone", "type": "zone"},
    "116": {"name": "Duct Zone", "type": "zone"},
    "117": {"name": "Flame Zone", "type": "zone"},
    "118": {"name": "Near Alarm Zone", "type": "zone"},
    "120": {"name": "Panic Zone", "type": "zone"},
    "121": {"name": "Duress User", "type": "user"},
    "122": {"name": "Silent Zone", "type": "zone"},
    "123": {"name": "Audible Zone", "type": "zone"},
    "124": {"name": "Duress – Access granted Zone", "type": "zone"},
    "125": {"name": "Duress – Egress granted Zone", "type": "zone"},
    "130": {"name": "Burglary Zone", "type": "zone"},
    "131": {"name": "Perimeter Zone", "type": "zone"},
    "132": {"name": "Interior Zone", "type": "zone"},
    "133": {"name": "24 Hour (Safe) Zone", "type": "zone"},
    "134": {"name": "Entry/Exit Zone", "type": "zone"},
    "135": {"name": "Day/night Zone", "type": "zone"},
    "136": {"name": "Outdoor Zone", "type": "zone"},
    "137": {"name": "Tamper Zone", "type": "zone"},
    "138": {"name": "Near alarm Zone", "type": "zone"},
    "139": {"name": "Intrusion Verifier Zone", "type": "zone"},
    "140": {"name": "General Alarm Zone", "type": "zone"},
    "141": {"name": "Polling loop open Zone", "type": "zone"},
    "142": {"name": "Polling loop short Zone", "type": "zone"},
    "143": {"name": "Expansion module failure Zone", "type": "zone"},
    "144": {"name": "Sensor tamper Zone", "type": "zone"},
    "145": {"name": "Expansion module tamper Zone", "type": "zone"},
    "146": {"name": "Silent Burglary Zone", "type": "zone"},
    "147": {"name": "Sensor Supervision Failure Zone", "type": "zone"},
    "150": {"name": "24 Hour Non-Burglary Zone", "type": "zone"},
    "151": {"name": "Gas detected Zone", "type": "zone"},
    "152": {"name": "Refrigeration Zone", "type": "zone"},
    "153": {"name": "Loss of heat Zone", "type": "zone"},
    "154": {"name": "Water Leakage Zone", "type": "zone"},
    "155": {"name": "Foil Break Zone", "type": "zone"},
    "156": {"name": "Day Trouble Zone", "type": "zone"},
    "157": {"name": "Low bottled gas level Zone", "type": "zone"},
    "158": {"name": "High temp Zone", "type": "zone"},
    "159": {"name": "Low temp Zone", "type": "zone"},
    "161": {"name": "Loss of air flow Zone", "type": "zone"},
    "162": {"name": "Carbon Monoxide detected Zone", "type": "zone"},
    "163": {"name": "Tank level Zone", "type": "zone"},
    "200": {"name": "Fire Supervisory Zone", "type": "zone"},
    "201": {"name": "Low water pressure Zone", "type": "zone"},
    "202": {"name": "Low CO2 Zone", "type": "zone"},
    "203": {"name": "Gate valve sensor Zone", "type": "zone"},
    "204": {"name": "Low water level Zone", "type": "zone"},
    "205": {"name": "Pump activated Zone", "type": "zone"},
    "206": {"name": "Pump failure Zone", "type": "zone"},
    "300": {"name": "System Trouble Zone", "type": "zone"},
    "301": {"name": "AC Loss Zone", "type": "zone"},
    "302": {"name": "Low system battery Zone", "type": "zone"},
    "303": {"name": "RAM Checksum bad Zone", "type": "zone"},
    "304": {"name": "ROM checksum bad Zone", "type": "zone"},
    "305": {"name": "System reset Zone", "type": "zone"},
    "306": {"name": "Panel programming changed Zone", "type": "zone"},
    "307": {"name": "Self-test failure Zone", "type": "zone"},
    "308": {"name": "System shutdown Zone", "type": "zone"},
    "309": {"name": "Battery test failure Zone", "type": "zone"},
    "310": {"name": "Ground fault Zone", "type": "zone"},
    "311": {"name": "Battery Missing/Dead Zone", "type": "zone"},
    "312": {"name": "Power Supply Overcurrent Zone", "type": "zone"},
    "313": {"name": "Engineer Reset User", "type": "user"},
    "320": {"name": "Sounder/Relay Zone", "type": "zone"},
    "321": {"name": "Bell 1 Zone", "type": "zone"},
    "322": {"name": "Bell 2 Zone", "type": "zone"},
    "323": {"name": "Alarm relay Zone", "type": "zone"},
    "324": {"name": "Trouble relay Zone", "type": "zone"},
    "325": {"name": "Reversing relay Zone", "type": "zone"},
    "326": {"name": "Notification Appliance Ckt. # 3 Zone", "type": "zone"},
    "327": {"name": "Notification Appliance Ckt. #4 Zone", "type": "zone"},
    "330": {"name": "System Peripheral trouble Zone", "type": "zone"},
    "331": {"name": "Polling loop open Zone", "type": "zone"},
    "332": {"name": "Polling loop short Zone", "type": "zone"},
    "333": {"name": "Expansion module failure Zone", "type": "zone"},
    "334": {"name": "Repeater failure Zone", "type": "zone"},
    "335": {"name": "Local printer out of paper Zone", "type": "zone"},
    "336": {"name": "Local printer failure Zone", "type": "zone"},
    "337": {"name": "Exp. Module DC Loss Zone", "type": "zone"},
    "338": {"name": "Exp. Module Low Batt. Zone", "type": "zone"},
    "339": {"name": "Exp. Module Reset Zone", "type": "zone"},
    "341": {"name": "Exp. Module Tamper Zone", "type": "zone"},
    "342": {"name": "Exp. Module AC Loss Zone", "type": "zone"},
    "343": {"name": "Exp. Module self-test fail Zone", "type": "zone"},
    "344": {"name": "RF Receiver Jam Detect Zone", "type": "zone"},
    "350": {"name": "Communication trouble Zone", "type": "zone"},
    "351": {"name": "Telco 1 fault Zone", "type": "zone"},
    "352": {"name": "Telco 2 fault Zone", "type": "zone"},
    "353": {"name": "Long Range Radio xmitter fault Zone", "type": "zone"},
    "354": {"name": "Failure to communicate event Zone", "type": "zone"},
    "355": {"name": "Loss of Radio supervision Zone", "type": "zone"},
    "356": {"name": "Loss of central polling Zone", "type": "zone"},
    "357": {"name": "Long Range Radio VSWR problem Zone", "type": "zone"},
    "370": {"name": "Protection loop Zone", "type": "zone"},
    "371": {"name": "Protection loop open Zone", "type": "zone"},
    "372": {"name": "Protection loop short Zone", "type": "zone"},
    "373": {"name": "Fire trouble Zone", "type": "zone"},
    "374": {"name": "Exit error alarm (zone) Zone", "type": "zone"},
    "375": {"name": "Panic zone trouble Zone", "type": "zone"},
    "376": {"name": "Hold-up zone trouble Zone", "type": "zone"},
    "377": {"name": "Swinger Trouble Zone", "type": "zone"},
    "378": {"name": "Cross-zone Trouble Zone", "type": "zone"},
    "380": {"name": "Sensor trouble Zone", "type": "zone"},
    "381": {"name": "Loss of supervision - RF Zone", "type": "zone"},
    "382": {"name": "Loss of supervision - RPM Zone", "type": "zone"},
    "383": {"name": "Sensor tamper Zone", "type": "zone"},
    "384": {"name": "RF low battery Zone", "type": "zone"},
    "385": {"name": "Smoke detector Hi sensitivity Zone", "type": "zone"},
    "386": {"name": "Smoke detector Low sensitivity Zone", "type": "zone"},
    "387": {"name": "Intrusion detector Hi sensitivity Zone", "type": "zone"},
    "388": {"name": "Intrusion detector Low sensitivity Zone", "type": "zone"},
    "389": {"name": "Sensor self-test failure Zone", "type": "zone"},
    "391": {"name": "Sensor Watch trouble Zone", "type": "zone"},
    "392": {"name": "Drift Compensation Error Zone", "type": "zone"},
    "393": {"name": "Maintenance Alert Zone", "type": "zone"},
    "400": {"name": "Open/Close User", "type": "user"},
    "401": {"name": "O/C by user User", "type": "user"},
    "402": {"name": "Group O/C User", "type": "user"},
    "403": {"name": "Automatic O/C User", "type": "user"},
    "404": {"name": "Late to O/C User", "type": "user"},
    "405": {"name": "Deferred O/C (Obsolete- do not use ) User", "type": "user"},
    "406": {"name": "Cancel User", "type": "user"},
    "407": {"name": "Remote arm/disarm User", "type": "user"},
    "408": {"name": "Quick arm User", "type": "user"},
    "409": {"name": "Keyswitch O/C User", "type": "user"},
    "411": {"name": "Callback request made User", "type": "user"},
    "412": {"name": "Successful download/access User", "type": "user"},
    "413": {"name": "Unsuccessful access User", "type": "user"},
    "414": {"name": "System shutdown command received User", "type": "user"},
    "415": {"name": "Dialer shutdown command received User", "type": "user"},
    "416": {"name": "Successful Upload Zone", "type": "zone"},
    "421": {"name": "Access denied User", "type": "user"},
    "422": {"name": "Access report by user User", "type": "user"},
    "423": {"name": "Forced Access Zone", "type": "zone"},
    "424": {"name": "Egress Denied User", "type": "user"},
    "425": {"name": "Egress Granted User", "type": "user"},
    "426": {"name": "Access Door propped open Zone", "type": "zone"},
    "427": {"name": "Access point Door Status Monitor trouble Zone", "type": "zone"},
    "428": {"name": "Access point Request To Exit trouble Zone", "type": "zone"},
    "429": {"name": "Access program mode entry User", "type": "user"},
    "430": {"name": "Access program mode exit User", "type": "user"},
    "431": {"name": "Access threat level change User", "type": "user"},
    "432": {"name": "Access relay/trigger fail Zone", "type": "zone"},
    "433": {"name": "Access RTE shunt Zone", "type": "zone"},
    "434": {"name": "Access DSM shunt Zone", "type": "zone"},
    "441": {"name": "Armed STAY User", "type": "user"},
    "442": {"name": "Keyswitch Armed STAY User", "type": "user"},
    "450": {"name": "Exception O/C User", "type": "user"},
    "451": {"name": "Early O/C User", "type": "user"},
    "452": {"name": "Late O/C User", "type": "user"},
    "453": {"name": "Failed to Open User", "type": "user"},
    "454": {"name": "Failed to Close User", "type": "user"},
    "455": {"name": "Auto-arm Failed User", "type": "user"},
    "456": {"name": "Partial Arm User", "type": "user"},
    "457": {"name": "Exit Error (user) User", "type": "user"},
    "458": {"name": "User on Premises User", "type": "user"},
    "459": {"name": "Recent Close User", "type": "user"},
    "461": {"name": "Wrong Code Entry Zone", "type": "zone"},
    "462": {"name": "Legal Code Entry User", "type": "user"},
    "463": {"name": "Re-arm after Alarm User", "type": "user"},
    "464": {"name": "Auto-arm Time Extended User", "type": "user"},
    "465": {"name": "Panic Alarm Reset Zone", "type": "zone"},
    "466": {"name": "Service On/Off Premises User", "type": "user"},
    "501": {"name": "Access reader disable Zone", "type": "zone"},
    "520": {"name": "Sounder/Relay Disable Zone", "type": "zone"},
    "521": {"name": "Bell 1 disable Zone", "type": "zone"},
    "522": {"name": "Bell 2 disable Zone", "type": "zone"},
    "523": {"name": "Alarm relay disable Zone", "type": "zone"},
    "524": {"name": "Trouble relay disable Zone", "type": "zone"},
    "525": {"name": "Reversing relay disable Zone", "type": "zone"},
    "526": {"name": "Notification Appliance Ckt. # 3 disable Zone", "type": "zone"},
    "527": {"name": "Notification Appliance Ckt. # 4 disable Zone", "type": "zone"},
    "531": {"name": "Module Added Zone", "type": "zone"},
    "532": {"name": "Module Removed Zone", "type": "zone"},
    "551": {"name": "Dialer disabled Zone", "type": "zone"},
    "552": {"name": "Radio transmitter disabled Zone", "type": "zone"},
    "553": {"name": "Remote Upload/Download disabled Zone", "type": "zone"},
    "570": {"name": "Zone/Sensor bypass Zone", "type": "zone"},
    "571": {"name": "Fire bypass Zone", "type": "zone"},
    "572": {"name": "24 Hour zone bypass Zone", "type": "zone"},
    "573": {"name": "Burg. Bypass Zone", "type": "zone"},
    "574": {"name": "Group bypass User", "type": "user"},
    "575": {"name": "Swinger bypass Zone", "type": "zone"},
    "576": {"name": "Access zone shunt Zone", "type": "zone"},
    "577": {"name": "Access point bypass Zone", "type": "zone"},
    "601": {"name": "Manual trigger test report Zone", "type": "zone"},
    "602": {"name": "Periodic test report Zone", "type": "zone"},
    "603": {"name": "Periodic RF transmission Zone", "type": "zone"},
    "604": {"name": "Fire test User", "type": "user"},
    "605": {"name": "Status report to follow Zone", "type": "zone"},
    "606": {"name": "Listen-in to follow Zone", "type": "zone"},
    "607": {"name": "Walk test mode User", "type": "user"},
    "608": {"name": "Periodic test - System Trouble Present Zone", "type": "zone"},
    "609": {"name": "Video Xmitter active Zone", "type": "zone"},
    "611": {"name": "Point tested OK Zone", "type": "zone"},
    "612": {"name": "Point not tested Zone", "type": "zone"},
    "613": {"name": "Intrusion Zone Walk Tested Zone", "type": "zone"},
    "614": {"name": "Fire Zone Walk Tested Zone", "type": "zone"},
    "615": {"name": "Panic Zone Walk Tested Zone", "type": "zone"},
    "616": {"name": "Service Request Zone", "type": "zone"},
    "621": {"name": "Event Log reset Zone", "type": "zone"},
    "622": {"name": "Event Log 50% full Zone", "type": "zone"},
    "623": {"name": "Event Log 90% full Zone", "type": "zone"},
    "624": {"name": "Event Log overflow Zone", "type": "zone"},
    "625": {"name": "Time/Date reset User", "type": "user"},
    "626": {"name": "Time/Date inaccurate Zone", "type": "zone"},
    "627": {"name": "Program mode entry Zone", "type": "zone"},
    "628": {"name": "Program mode exit Zone", "type": "zone"},
    "629": {"name": "32 Hour Event log marker Zone", "type": "zone"},
    "630": {"name": "Schedule change Zone", "type": "zone"},
    "631": {"name": "Exception schedule change Zone", "type": "zone"},
    "632": {"name": "Access schedule change Zone", "type": "zone"},
    "641": {"name": "Senior Watch Trouble Zone", "type": "zone"},
    "642": {"name": "Latch-key Supervision User", "type": "user"},
    "651": {"name": "Reserved for Ademco Use Zone", "type": "zone"},
    "652": {"name": "Reserved for Ademco Use User", "type": "user"},
    "653": {"name": "Reserved for Ademco Use User", "type": "user"},
    "654": {"name": "System Inactivity", "type": "zone"},
}
